from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    ListFlowable,
    ListItem
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from io import BytesIO
from datetime import datetime


def generate_pdf_report(data: dict):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=30
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        alignment=1,
        textColor=colors.darkblue,
        fontSize=22,
        spaceAfter=20
    )

    section_title = ParagraphStyle(
        "SectionTitle",
        parent=styles["Heading3"],
        textColor=colors.darkblue,
        spaceAfter=10
    )

    normal = styles["Normal"]

    elements = []

    # ---------------- HEADER ----------------

    elements.append(
        Paragraph("Arogya Raksha - AI Health Risk Assessment Report", title_style)
    )

    elements.append(
        Paragraph(
            f"Generated on: {datetime.now().strftime('%d %B %Y, %H:%M')}",
            normal
        )
    )

    elements.append(Spacer(1, 20))

    # ---------------- RISK SUMMARY TABLE ----------------

    risk_data = [
        ["Risk Score", data.get("risk_score")],
        ["Classification", data.get("classification")],
        ["Predicted Condition", data.get("predicted_condition")],
        ["Confidence", f"{data.get('confidence')}%"],
        ["Recommendation", data.get("recommendation")]
    ]

    risk_table = Table(risk_data, colWidths=[200, 300])

    risk_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.lightblue),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
            ("GRID", (0, 0), (-1, -1), 1, colors.grey),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("PADDING", (0, 0), (-1, -1), 8),
        ])
    )

    elements.append(Paragraph("Risk Summary", section_title))
    elements.append(risk_table)

    elements.append(Spacer(1, 20))

    # ---------------- SYMPTOMS ----------------

    contributors = data.get("contributors", [])

    if contributors:

        elements.append(Paragraph("Detected Symptoms", section_title))

        symptom_list = [
            ListItem(Paragraph(symptom, normal))
            for symptom in contributors
        ]

        elements.append(
            ListFlowable(symptom_list, bulletType="bullet")
        )

        elements.append(Spacer(1, 20))

    # ---------------- AI EXPLANATION ----------------

    explanation = data.get("explanation")

    if explanation:

        elements.append(Paragraph("AI Explanation", section_title))
        elements.append(Paragraph(explanation, normal))

        elements.append(Spacer(1, 20))

    # ---------------- PATIENT GUIDANCE ----------------

    education = data.get("patient_education")

    if education:

        elements.append(Paragraph("Patient Guidance", section_title))
        elements.append(Paragraph(education, normal))

        elements.append(Spacer(1, 20))

    # ---------------- DISCLAIMER ----------------

    disclaimer = data.get("disclaimer")

    if disclaimer:

        elements.append(Paragraph("Medical Disclaimer", section_title))

        elements.append(
            Paragraph(
                disclaimer,
                ParagraphStyle(
                    "disclaimer",
                    parent=normal,
                    textColor=colors.red,
                    fontSize=9
                )
            )
        )

    elements.append(Spacer(1, 30))

    # ---------------- FOOTER ----------------

    footer = Paragraph(
        "This report is generated by Arogya Raksha AI system for early risk screening and does not replace professional medical diagnosis.",
        ParagraphStyle(
            "footer",
            parent=normal,
            alignment=1,
            fontSize=8,
            textColor=colors.grey
        )
    )

    elements.append(footer)

    doc.build(elements)

    buffer.seek(0)

    return buffer